FROM ruby:2.6.6-alpine3.10

ENV APP_PATH /project
ENV PATH "${PATH}:${APP_PATH}/bin"
WORKDIR $APP_PATH

RUN apk --update add make g++ postgresql-dev build-base bash nodejs npm yarn \
  && gem install bundler \
  && echo "user:x:1000:1000::/project/docker/development/home:/bin/zsh" >> /etc/passwd \
  && apk add --update micro --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing \
  && apk add --update zsh git openssh

COPY Gemfile $APP_PATH
COPY Gemfile.lock $APP_PATH
RUN bundle install

COPY package.json $APP_PATH
COPY package-lock.json $APP_PATH
RUN npm install

COPY . $APP_PATH

CMD [ "puma" ]

EXPOSE 3000