version: "3"

services:
  padrino:
    container_name: padrino-web
    build:
      dockerfile: docker/Dockerfile
      context: .
    image: where_to_work_padrino
    volumes:
      - .:/project
    ports:
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    container_name: padrino-mongo
    image: mongo:latest
    volumes:
      - ./data/mongo:/data/db
    restart: always
    ports:
      - 27017:27017