version: "3"

services:
    rails:
        container_name: where-to-code-rails
        build:
            context: .
        image: rails_where_to_code
        volumes:
            - .:/project
        ports:
            - "3000:3000"
        depends_on:
            - postgres
            - redis

    postgres:
        container_name: where-to-code-postgres
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - $HOME/.docker/data/where-to-code/postgres:/var/lib/postgresql/data

    redis:
        container_name: "where-to-code-redis"
        image: redis
        restart: always
        volumes:
            - $HOME/.docker/data/where-to-code/redis:/data