version: '3'

services:
  rails:
    container_name: where-to-code-rails
    build:
      dockerfile: docker/development/dockerfile
      context: .
    stdin_open: true
    tty: true
    user: user
    volumes:
      - .:/project
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: where-to-code-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/development/data/postgres:/var/lib/postgresql/data

  redis:
    container_name: where-to-code-redis
    image: redis
    volumes:
      - ./docker/development/data/redis:/data