version: "3"

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "3001:8081"