efault: &default
  host: 127.0.0.1
  username: root
  password: root
  database: where-to-code
  adapter: mysql2

development:
  <<: *default
  host: 127.0.0.1
  username: root
  password: root
  database: where-to-code
  adapter: mysql2
